### ISSUE TITLE
Feature Request: Infobox timer like in Frozen Cookies

### ISSUE THREAD

**Issue by korewaChino** [elliotks/ACABM#3]
Instead of putting building times as a toast, put them as an overlay infobox like in the Frozen Cookies mod.

**Comment by elliotks** [comment]
Hello @korewaChino 

I will need to review further to get a visual representation / better understanding of this request. 

As far as a timeframe for me to implement this enhancement, It depends on the amount of work required - which I should have a better idea on once I dig into the Frozen Cookies mod. 

Thank you!

**Comment by korewaChino** [comment]
> I will need to review further to get a visual representation / better understanding of this request.

I meant, instead of popping up toasts, we can have an overlay that looks like this instead:

![image](https://github.com/elliotks/ACABM/assets/38139192/00bf6d52-66ca-4cf3-96a9-8ee266a8e6f8)

This will provide a better way to track building times instead of consistently refreshing.

The wheel also gives you a good progress of the timer.

**Comment by elliotks** [comment]
I see now, thank you for clarifying. I am assuming you have ACABM "hotkeys" option enabled? For that, I apologize lol - that was before the GUI in the options menu was implemented.

I'll see what I can come up with, the biggest reason why I haven't taken any of the games main views to display information is because of possible mod conflicts for the position it would be displayed at. I guess I could make it an option for people to turn on or off. 

This will end up being lower on the priority list.

**Comment by elliotks** [comment]
ACABM v3 track - Added a draggable pop-up window with Auto Buy status
![image](https://github.com/elliotks/ACABM/assets/10646544/4bd429fc-7a97-45cd-af1c-be62180ed7b6)
